"""
pose_estimation.py — FormaFix
==============================
Standalone mode: select one exercise from the CLI and run live pose tracking.
Press Q to quit, R to reset the rep counter.

After the session ends a progress report is generated by the AI agent.
"""

import os
import urllib.request

import cv2
import mediapipe as mp

from angle_calculator import get_all_angles
from audio_feedback import AudioFeedback
from exercise_selector import select_exercise
from feedback_engine import FeedbackEngine
from form_evaluator import FormEvaluator
from progress_agent import ProgressSummaryAgent
from rep_counter import RepCounter

# ── MediaPipe setup ──────────────────────────────────────────────────────────
BaseOptions          = mp.tasks.BaseOptions
PoseLandmarker       = mp.tasks.vision.PoseLandmarker
PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
VisionRunningMode    = mp.tasks.vision.RunningMode

MODEL_PATH = "pose_landmarker.task"
MODEL_URL  = (
    "https://storage.googleapis.com/mediapipe-models/"
    "pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task"
)


def _ensure_model() -> str:
    """Download the MediaPipe model if it is not already present."""
    if not os.path.exists(MODEL_PATH):
        print("Downloading pose model...")
        urllib.request.urlretrieve(MODEL_URL, MODEL_PATH)
        print("Model downloaded!")
    return MODEL_PATH


# ── Skeleton connections (MediaPipe landmark indices) ────────────────────────
CONNECTIONS = [
    (11, 12), (11, 13), (13, 15),
    (12, 14), (14, 16),
    (11, 23), (12, 24), (23, 24),
    (23, 25), (25, 27),
    (24, 26), (26, 28),
]

# ── Which joint to track for each exercise ───────────────────────────────────
EXERCISE_JOINT: dict[str, str] = {
    "straight_leg_raise":      "left_hip",
    "terminal_knee_extension": "left_knee",
    "mini_squat":              "left_knee",
    "hamstring_curl":          "left_knee",
    "pendulum":                "left_shoulder",
    "external_rotation":       "left_elbow",
    "wall_slide":              "left_shoulder",
    "shoulder_abduction":      "left_shoulder",
    "bicep_curl":              "left_elbow",
    "squat":                   "left_knee",
    "shoulder_raise":          "left_shoulder",
}


def run_pose_estimation(exercise_info: dict) -> None:
    """
    Run live pose estimation for the selected exercise.

    Parameters
    ----------
    exercise_info : dict from exercise_selector.select_exercise()
        keys: name, joint, display
    """
    exercise_name    = exercise_info["name"]
    exercise_display = exercise_info["display"]
    joint_key        = EXERCISE_JOINT.get(exercise_name, "left_elbow")

    # ── Session data collectors ──────────────────────────────────────────────
    all_scores: list[int] = []
    max_angle_reached: float = 0.0

    # ── Component instances ──────────────────────────────────────────────────
    counter      = RepCounter()
    evaluator    = FormEvaluator()
    feedback_eng = FeedbackEngine()
    audio        = AudioFeedback()

    _ensure_model()
    options = PoseLandmarkerOptions(
        base_options=BaseOptions(model_asset_path=MODEL_PATH),
        running_mode=VisionRunningMode.IMAGE,
    )

    cap = cv2.VideoCapture(0)

    with PoseLandmarker.create_from_options(options) as landmarker:
        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            h, w, _ = frame.shape
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            mp_image  = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb_frame)
            results   = landmarker.detect(mp_image)

            if results.pose_landmarks:
                landmarks = results.pose_landmarks[0]

                # Draw skeleton
                for start, end in CONNECTIONS:
                    x1, y1 = int(landmarks[start].x * w), int(landmarks[start].y * h)
                    x2, y2 = int(landmarks[end].x * w),   int(landmarks[end].y * h)
                    cv2.line(frame, (x1, y1), (x2, y2), (255, 255, 0), 2)
                for lm in landmarks:
                    cv2.circle(frame, (int(lm.x * w), int(lm.y * h)), 5, (0, 255, 0), -1)

                # Calculate joint angles
                angles        = get_all_angles(landmarks, w, h)
                current_angle = angles[joint_key]

                # Track session statistics
                all_scores.append(int(current_angle))          # placeholder; replaced below
                if current_angle > max_angle_reached:
                    max_angle_reached = current_angle

                # Rep counting
                reps, stage = counter.count(current_angle)

                # Form scoring
                score, form_feedback = evaluator.evaluate(exercise_name, joint_key, current_angle)
                all_scores[-1] = score  # correct the appended value

                # Coaching cue
                tip = feedback_eng.get_feedback(exercise_name, angles)

                # Speak correction when form is poor
                if score < 75:
                    audio.speak(tip)

                # ── HUD ──────────────────────────────────────────────────────
                cv2.putText(frame, f"Exercise: {exercise_display}",
                            (10, 30),  cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
                cv2.putText(frame, f"{joint_key}: {current_angle}°",
                            (10, 65),  cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)
                cv2.putText(frame, f"Reps: {reps}",
                            (10, 100), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 255, 255), 3)
                cv2.putText(frame, f"Stage: {stage or 'ready'}",
                            (10, 140), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2)
                cv2.putText(frame, f"Score: {score}/100",
                            (10, 180), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
                cv2.putText(frame, form_feedback,
                            (10, 215), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
                cv2.putText(frame, tip,
                            (10, 250), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 165, 255), 2)
                cv2.putText(frame, "Press R to reset | Q to quit",
                            (10, h - 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (200, 200, 200), 1)

            cv2.imshow("FormaFix", frame)

            key = cv2.waitKey(10) & 0xFF
            if key == ord("q"):
                break
            elif key == ord("r"):
                counter.reset()

    cap.release()
    cv2.destroyAllWindows()

    # ── Post-session AI report ───────────────────────────────────────────────
    if all_scores:
        avg_score = round(sum(all_scores) / len(all_scores))
        session_results = {
            "exercise_name": exercise_display,
            "reps":          counter.counter,
            "avg_score":     avg_score,
            "best_angle":    round(max_angle_reached, 1),
        }
        print("\n" + "=" * 40)
        print("📝 GENERATING PROGRESS SUMMARY...")
        try:
            report = ProgressSummaryAgent().generate_report(session_results)
            print("-" * 40)
            print(report)
        except Exception as e:
            print(f"[Warning] Could not generate AI report: {e}")
        print("=" * 40 + "\n")


if __name__ == "__main__":
    exercise = select_exercise()
    run_pose_estimation(exercise)
